#!/usr/bin/env bash
# Configure a domain zone
# Usage: ./0-world_wide_web <domain> <subdomain>
domain_info() {
	#DNS Look-up
	output=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $output" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

#inspect args parsed
if [ "$#" == 1 ]
then
	domain_info "$1" "www"
	domain_info "$1" "lb-01"
	domain_info "$1" "web-01"
	domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
	domain_info "$1" "$2"
fi
