#!/usr/bin/env bash
# Performing redirections

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=c7DIvNmMPkc&list=PL-h6GwC7HdreutdAfv0SX85G93GpRrYKC permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
