#!/usr/bin/env bash
# Performing redirections

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
CONFIG_RE="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$CONFIG_RE/" /etc/nginx/sites-enabled/default
sudo service nginx restart
