#!/usr/bin/env bash
# Not found page 404

sudo apt-get update
sudo apt-get install -y nginx

sudo echo "Hello World!" | sudo tee /var/www/html/index.html

CONFIG_RE="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$CONFIG_RE/" /etc/nginx/sites-enabled/default

sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
CONFIG_404="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$CONFIG_404/" /etc/nginx/sites-available/default
sudo service nginx restart
