#!/usr/bin/env bash
# configure HAproxy on your lb-01 server.
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt update
sudo apt install -y haproxy
CONFIG_LB="\
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend web-servers
    
backend web-servers
    balance roundrobin
    server 321565-web-01 35.168.3.7:80 check
    server 321565-web-02 100.25.170.135:80 check
"
sudo echo "$CONFIG_LB" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
