#!/usr/bin/env bash
# Making fix short and sweet.

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# Now kill nginx process
kill "$(pgrep 'nginx' | head -1)"
