#!/usr/bin/env bash
#A script that creates, displays, deletes and terminates itself

str="1"
sudo touch /var/run/holbertonscript.pid

trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit' SIGTERM
trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT
echo $$ > /var/run/holbertonscript.pid
while [ $str -ne 0 ]
do
	echo "To infinity and beyond"
	sleep 2
done
