#!/usr/bin/env bash
#A script that controls 'manage_my_process'

st="start"
stp="top"
rst="restart"
if [ "${1}" == "$st" ]
then
	./manage_my_process & pid_file=/var/run/my_process.pid
	echo "$!" > pid_file
	echo "manage_my_process started"
elif [ "${1}" == "$stp" ]
then
	echo "manage_my_process stopped"
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
elif [ "${1}" == "$rst" ]
then
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process & pid_file=/var/run/my_process.pid
	echo "$!" > pid_file
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
