#!/usr/bin/env bash
# Displays Best School 10 times.

counter=10
while [ $counter \> 0 ]
do
if [ $counter \= 7]
then
	echo "bad luck"
elif [ $counter \= 3]
then
	echo "good luck"
else
	echo "Best School"
fi
	((counter--))
done
