#!/usr/bin/env bash
# Displays Best School 10 times.


counter=10
while [ $counter -gt 0 ]
do
if [ $counter -eq 7 ];
then
	echo "bad luck"
elif [ $counter -eq 3 ];
then
	echo "good luck"
else
	echo "Best School"
fi
	(( counter-- ))
done
