#!/usr/bin/env bash
# Displays  the time for 12 hours and 59 minutes


hr=0

while [ $hr -le 12 ]
do
	echo "Hour: $hr"
	mn=1
	while [ $mn -le 59 ]
	do
		echo "$mn"
		(( mn++ ))
	done
	(( hr++ ))
done
