#!/usr/bin/env bash
# Displays The content of the current directory

for file in *
do
    if [[ -f "$file" ]]; then  # Check if it's a regular file
        echo "$file" | cut -d '-' -f2
    elif [[ -d "$file" ]]; then  # Check if it's a directory
        echo "[$file]"
    fi
done
