#!/usr/bin/env bash
# Displays the content of the current directory in a list format

for file in *
do
    # Check if it's a regular file, not hidden, and contains a dash
    if [[ -f "$file" && ! "$file" =~ ^. && "$file" =~ - ]]; then
        # Use cut to extract the part after the first dash
        name=$(echo "$file" | cut -d '-' -f2-)
        echo "$name"
    fi
done
